### ISSUE TITLE
how to set custom data attributes rails selectize

### ISSUE THREAD

**Issue by Qubaish** [manuelvanrijn/selectize-rails#18] opened 2018-05-03 14:24 UTC
Hi guys, I am trying to set data attributes for selectize but it did'nt work. I tried different solutions but no success. Here is one solution that I tried.

HTML

`	select_tag "permission_group[users][]", 
	options_for_select(@usersusers.collect{ |u| [u["first_name"], u["id"], {"data-type" => "test"}] }), 
	class: 'permission', 
	multiple: true`

JS
`
$(".permission").selectize
    render:
        option: (data) ->
            console.log(data); /// {label: "qubaush", value: "10538", $order: 3} (this is the console data )
            """<div><span class="title"><span class="name">hello</span></span></div>"""
`

Can you please tell me what I did wrong. 
Thanks

**Comment by manuelvanrijn** [comment] 2018-09-19 07:31
Hi!

Maybe you can assign your question about the plugin to the original maintainer :) https://github.com/selectize/selectize.js

**Comment by manuelvanrijn** [comment] 2018-11-07 07:37
For now I'll close this issue. Please reopen if the problem is part of this gem

**Closed by manuelvanrijn** 2018-11-07 07:37 UTC
